version: '3.8'

services:
  video-recorder-monitor:
    image: video-recorder-monitor:latest
    build: .
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - PRIMARY_API_BASE_URL=https://IP-of-PLaybox-ingest:4230
      - DVR_API_BASE_URL=http://ip-of-MovieRecorder:8080
      - POLL_INTERVAL=5
      - FLASK_PORT=8001
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
